// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Force hardcoded credentials for production deployment
const SUPABASE_URL = "https://tvyhhtqyvxjacywugilj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2eWhodHF5dnhqYWN5d3VnaWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyNTIzMDksImV4cCI6MjA5NTgyODMwOX0.J5Q459OMzaPZLJioyOq_7YyUKiUHUSM_193M37y4HyQ";

function createSupabaseClient() {
  console.log("[Supabase] Initializing with hardcoded values");

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
